/**
 * R117's guard: a `<file>.<ext>:<line>` pointer written into a comment or a doc rots silently.
 *
 * The measured failure mode is not that somebody wrote a wrong number. It is that the number was
 * RIGHT when written and an unrelated edit moved the target, so the pointer keeps reading as
 * evidence while pointing at something else. Two of the four measured instances invalidated their
 * own pointer in the commit that wrote them — one comment pushed its own target down by exactly
 * its own length. Nothing in the repo could see that happen, so it kept happening; the previous
 * session added more citations while writing about the ones it was fixing.
 *
 * The rule: **cite greppable NAMES, never line numbers.** Every target in every measured instance
 * was uniquely greppable (a declaration name, a pushed string literal, a section heading), and the
 * repo already does this correctly in places.
 *
 * Two scope decisions, made deliberately rather than fallen into:
 *
 * 1. **Same-file citations are banned too, not only cross-file ones.** The worst measured instance
 *    was a file citing ITSELF: a twelve-line comment quoting a line number twelve lines below,
 *    which its own insertion had already pushed out from under it. Same-file pointers rot at least
 *    as easily as cross-file ones, and they are no harder to replace with a name.
 *
 * 2. **This is a test, not a lint rule.** Biome 1.9 (this repo's linter) has no custom-rule
 *    mechanism, so a lint rule would mean a second linter. A test also gets to fail on the ALLOWLIST
 *    rotting, which a lint rule could not express.
 *
 * Historical records are exempt by directory rather than by allowlist entry, because their bodies
 * must not be rewritten at all: sealed campaign pre-commitments, and dated plans and specs whose
 * whole value is being what was written on that date. A pointer inside one of those is a record of
 * a claim, not a claim being made now.
 */

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { Glob } from "bun";

/**
 * File extensions whose `name.ext:123` form counts as a citation.
 *
 * `.al` is included even though LethAL's own mutant-site output is literally `file:line`, because
 * AL source pointers in comments rot exactly like TypeScript ones. Example output that happens to
 * contain a mutant site is handled by {@link ALLOWLIST}, where each one carries its reason.
 */
const CITED_EXTENSIONS = ["ts", "al", "md"] as const;

/** Matches a bare `basename.ext:123`, with or without a directory prefix in front of it. */
export const CITATION_PATTERN = new RegExp(
  `[A-Za-z0-9_][A-Za-z0-9_.-]*\\.(?:${CITED_EXTENSIONS.join("|")}):\\d+`,
  "g",
);

/** Globs, relative to the repo root, whose files are scanned. */
export const SCANNED_GLOBS: readonly string[] = [
  "*.md",
  "packages/*/src/**/*.ts",
  "packages/*/tests/**/*.ts",
  "packages/*/itest/**/*.ts",
  "scripts/**/*.ts",
  "docs/*.md",
  "docs/roadmap/*.md",
  "docs/measurements/*.md",
  "fixtures/**/README.md",
];

/**
 * Path prefixes skipped even when a scanned glob reaches them. Each is a RECORD whose body must
 * not be rewritten, so a pointer inside one cannot be fixed and must not be reported as fixable.
 */
export const EXEMPT_PREFIXES: readonly { prefix: string; reason: string }[] = [
  {
    prefix: "docs/campaign/",
    reason: "sealed pre-commitment records — corrections go in that directory's README",
  },
  {
    prefix: "docs/superpowers/plans/",
    reason: "dated plans — a record of what was planned on a date; add a header, never rewrite",
  },
  {
    prefix: "docs/superpowers/specs/",
    reason: "dated specs — same rule as plans",
  },
  {
    prefix: "scripts/line-citations",
    reason:
      "the guard and its test necessarily spell out citation-shaped strings as examples and as fixtures",
  },
  { prefix: "node_modules/", reason: "third-party sources, not written here" },
  { prefix: "scripts/dist/", reason: "build output, regenerated by `tsc --build`" },
];

export interface Citation {
  /** Repo-relative path with forward slashes. */
  readonly file: string;
  /** 1-based line number the citation sits on. */
  readonly line: number;
  /** The matched text, e.g. `report.ts:918`. */
  readonly text: string;
}

/**
 * Citations that are deliberately kept, keyed by file and by the citation TEXT rather than by the
 * line it sits on — an allowlist keyed on a line number would rot the same way the citations do.
 */
export const ALLOWLIST: readonly { file: string; citation: string; reason: string }[] = [
  {
    file: "README.md",
    citation: "Pricing.Codeunit.al:5",
    reason:
      "sample `lethal run` output; `file:line` is LethAL's own mutant-site column, not a pointer",
  },
  {
    file: "docs/releasing.md",
    citation: "SandboxLogic.Codeunit.al:4",
    reason: "sample `lethal run` output from the release smoke test, pasted verbatim",
  },
  {
    file: "docs/roadmap/R036.md",
    citation: "DataOps.Codeunit.al:44",
    reason: "a MUTANT SITE (M0034), which is `file:line` by definition — not a pointer at prose",
  },
  {
    file: "docs/roadmap/R085.md",
    citation: "Handler.al:187",
    reason: "a mutant site measured in a customer project this repo does not contain",
  },
  // The rows and the comment below REPORT rotted pointers, quoting the old and new numbers as the
  // measurement. Rewriting those to names would delete the evidence that the rot happened.
  {
    file: "docs/roadmap/R113.md",
    citation: "report.ts:918",
    reason: "quoted as the measured FALSE citation the row exists to report",
  },
  {
    file: "docs/roadmap/R117.md",
    citation: "report.ts:918",
    reason: "quoted as measured instance (1) of the rot this guard now prevents",
  },
  {
    file: "docs/roadmap/R117.md",
    citation: "report.ts:194",
    reason: "quoted as measured instance (2)",
  },
  {
    file: "docs/roadmap/R117.md",
    citation: "orchestrator.ts:2360",
    reason: "quoted as measured instance (4)",
  },
  {
    file: "packages/runner/src/interpretation.ts",
    citation: "report.ts:194",
    reason:
      "the comment's subject IS the rot: it records what this pointer used to read and why it now cites a name",
  },
];

/** True when `file` sits under a prefix that is exempt by rule. */
export function isExempt(file: string): boolean {
  return EXEMPT_PREFIXES.some(({ prefix }) => file.startsWith(prefix));
}

/** Every citation in one file's text, with 1-based line numbers. */
export function findCitations(file: string, text: string): Citation[] {
  const found: Citation[] = [];
  const lines = text.split("\n");
  for (const [index, line] of lines.entries()) {
    for (const match of line.matchAll(CITATION_PATTERN)) {
      found.push({ file, line: index + 1, text: match[0] });
    }
  }
  return found;
}

/** True when this exact (file, citation text) pair is on the allowlist. */
export function isAllowlisted(citation: Citation): boolean {
  return ALLOWLIST.some(
    (entry) => entry.file === citation.file && entry.citation === citation.text,
  );
}

/** Every scanned file in the repo, repo-relative, forward-slashed, sorted. */
export function scannedFiles(root: string): string[] {
  const seen = new Set<string>();
  for (const pattern of SCANNED_GLOBS) {
    for (const hit of new Glob(pattern).scanSync({ cwd: root, onlyFiles: true })) {
      const normalized = hit.replaceAll("\\", "/");
      if (!isExempt(normalized)) seen.add(normalized);
    }
  }
  return [...seen].sort();
}

/** Every citation in the repo that is not exempt by directory. */
export function scanRepo(root: string): Citation[] {
  return scannedFiles(root).flatMap((file) =>
    findCitations(file, readFileSync(join(root, file), "utf8")),
  );
}
