#!/usr/bin/env bun
/**
 * RUST-01: the license and notice inventory for the native parser addon. Lists every crate cargo
 * resolves, evaluates each FULL SPDX expression (OR needs one allowed side, AND needs both, WITH
 * needs an allowed exception), and writes packages/engine/native/THIRD-PARTY-NOTICES.md.
 * `--check` exits 1 if the committed file differs.
 *
 *   bun scripts/native-notices.ts [--check]
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { CRATE, cargoPackages } from "./check-native-grammar";

const ALLOWED = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "0BSD",
];
const ALLOWED_EXCEPTIONS = ["LLVM-exception"];
const OUT = join(CRATE, "THIRD-PARTY-NOTICES.md");

export function spdxAllowed(expr: string): boolean {
  const tokens = expr
    .replaceAll("/", " OR ")
    .replaceAll("(", " ( ")
    .replaceAll(")", " ) ")
    .split(/\s+/)
    .filter(Boolean);
  if (tokens.length === 0) return false;
  let pos = 0;
  const atom = (): boolean => {
    const t = tokens[pos++];
    if (t === undefined) throw new Error(`truncated SPDX expression: ${expr}`);
    if (t === "(") {
      const v = orExpr();
      if (tokens[pos++] !== ")") throw new Error(`unbalanced SPDX expression: ${expr}`);
      return v;
    }
    return ALLOWED.includes(t);
  };
  const withExpr = (): boolean => {
    const v = atom();
    if (tokens[pos] !== "WITH") return v;
    pos++;
    const exception = tokens[pos++];
    return v && exception !== undefined && ALLOWED_EXCEPTIONS.includes(exception);
  };
  const andExpr = (): boolean => {
    let v = withExpr();
    while (tokens[pos] === "AND") {
      pos++;
      const r = withExpr();
      v = v && r;
    }
    return v;
  };
  const orExpr = (): boolean => {
    let v = andExpr();
    while (tokens[pos] === "OR") {
      pos++;
      const r = andExpr();
      v = v || r;
    }
    return v;
  };
  const v = orExpr();
  if (pos !== tokens.length) throw new Error(`unparsed tail in SPDX expression: ${expr}`);
  return v;
}

if (import.meta.main) {
  const rows = cargoPackages()
    .filter((p) => p.name !== "lethal-parser")
    .map((p) => ({ name: p.name, version: p.version, license: p.license ?? "" }))
    .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
  const bad = rows.filter((r) => !spdxAllowed(r.license));
  if (bad.length > 0)
    throw new Error(
      `licenses outside the allowlist: ${bad.map((r) => `${r.name} ${r.version} (${r.license || "none"})`).join(", ")}`,
    );
  const text = [
    "# Third-party notices: LethAL native parser addon",
    "",
    "Generated by `bun scripts/native-notices.ts` from `cargo metadata`. Do not edit by hand.",
    "The grammar (tree-sitter-al, MIT) and the tree-sitter runtime (MIT) are compiled into the addon.",
    "",
    "| crate | version | license |",
    "| --- | --- | --- |",
    ...rows.map((r) => `| ${r.name} | ${r.version} | ${r.license} |`),
    "",
  ].join("\n");
  if (process.argv.includes("--check")) {
    if (readFileSync(OUT, "utf8").replaceAll("\r", "") !== text) {
      console.error("THIRD-PARTY-NOTICES.md is out of date: run bun scripts/native-notices.ts");
      process.exit(1);
    }
  } else {
    writeFileSync(OUT, text);
  }
}
